document.write( '<!-- Footer -->\n' );
document.write( '<footer class=\"page-footer font-small unique-color-dark\">\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '  <!-- Footer Links -->\n' );
document.write( '  <div class=\"container text-center text-md-left mt-5\">\n' );
document.write( 'sr.reveal(\".carousel\", {\n' );
document.write( '        duration:2000,\n' );
document.write( '        origin:\"rigth\",\n' );
document.write( '        distance:\"300px\"\n' );
document.write( '      });\n' );
document.write( '    <!-- Grid row -->\n' );
document.write( '    <div class=\"row mt-3\">\n' );
document.write( '\n' );
document.write( '      <!-- Grid column -->\n' );
document.write( '      <div class=\"col-md-3 col-lg-4 col-xl-3 mx-auto mb-4\">\n' );
document.write( '\n' );
document.write( '        <!-- Content -->\n' );
document.write( '        <h6 class=\"text-uppercase font-weight-bold\">PINTURAS CONTIMEX</h6>\n' );
document.write( '        <hr class=\"deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto\" style=\"width: 60px;\">\n' );
document.write( '        <p class=\"descripcion\">Pinturas Contimex, S.A de C.V. es una compañia 100% mexicana\n' );
document.write( '        y fué fundada en el año de 1963, está consolidada a fin de poder ofrecer al mercado\n' );
document.write( '      pinturas de la más alta calidad, especialmente en el rubro de pinturas\n' );
document.write( '    arquitectónicas, además de todo tipo de especialidades para la industria\n' );
document.write( '  de tal manera que en la actualidad le suministramos a diferentes empresas transnacionales\n' );
document.write( 'lo cual nos ha dado el prestigio suficiente para que todos nuestros clientes sientan la\n' );
document.write( 'confianza de poder continuar trabajando con nosotros.</p>\n' );
document.write( '\n' );
document.write( '      </div>\n' );
document.write( '      <!-- Grid column -->\n' );
document.write( '\n' );
document.write( '      <!-- Grid column -->\n' );
document.write( '      <div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\n' );
document.write( '\n' );
document.write( '        <!-- Links -->\n' );
document.write( '        <h6 class=\"text-uppercase font-weight-bold\">PRODUCTOS</h6>\n' );
document.write( '        <hr class=\"deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto\" style=\"width: 60px;\">\n' );
document.write( '        <p>\n' );
document.write( '          <a class=\"links\" href=\"vinilicas.html\">Vinilicas</a>\n' );
document.write( '        </p>\n' );
document.write( '        <p>\n' );
document.write( '          <a class=\"links\" href=\"esmaltes.html\">Esmaltes</a>\n' );
document.write( '        </p>\n' );
document.write( '        <p>\n' );
document.write( '          <a class=\"links\" href=\"impermeabilizantes.html\">Impermeabilizantes</a>\n' );
document.write( '        </p>\n' );
document.write( '        <p>\n' );
document.write( '          <a class=\"links\" href=\"pegamentos.html\">Pegamentos y selladores</a>\n' );
document.write( '        </p>\n' );
document.write( '        <p>\n' );
document.write( '          <a class=\"links\" href=\"especialidades.html\">Especialidades</a>\n' );
document.write( '        </p>\n' );
document.write( '        <p>\n' );
document.write( '          <a class=\"links\" href=\"industrial.html\">Industriales</a>\n' );
document.write( '        </p>\n' );
document.write( '\n' );
document.write( '      </div>\n' );
document.write( '      <!-- Grid column -->\n' );
document.write( '\n' );
document.write( '      <!-- Grid column -->\n' );
document.write( '      <div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\n' );
document.write( '\n' );
document.write( '        <!-- Links -->\n' );
document.write( '        <h6 class=\"text-uppercase font-weight-bold\">EMPRESA</h6>\n' );
document.write( '        <hr class=\"deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto\" style=\"width: 60px;\">\n' );
document.write( '        <p>\n' );
document.write( '          <a class=\"links\" href=\"#!\">Términos y condiciones</a>\n' );
document.write( '        </p>\n' );
document.write( '        <p>\n' );
document.write( '          <a class=\"links\" href=\"#!\">Bolsa de trabajo</a>\n' );
document.write( '        </p>\n' );
document.write( '        <p>\n' );
document.write( '          <a class=\"links\"  href=\"#!\">Aviso de privacidad</a>\n' );
document.write( '        </p>\n' );
document.write( '      </div>\n' );
document.write( '      <!-- Grid column -->\n' );
document.write( '\n' );
document.write( '      <!-- Grid column -->\n' );
document.write( '      <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4\">\n' );
document.write( '\n' );
document.write( '        <!-- Links -->\n' );
document.write( '        <h6 class=\"text-uppercase font-weight-bold\">CONTACTO</h6>\n' );
document.write( '        <hr class=\"deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto\" style=\"width: 60px;\">\n' );
document.write( '        <p class=\"direccion\">\n' );
document.write( '          <i class=\"datos fas fa-home mr-3\"></i>Calzada San Lorenzo No. 966 Col. San Nicolás\n' );
document.write( '        Tolentino, C.P. 09850 Deleg. Iztapalapa CDMX</p>\n' );
document.write( '        <p class=\"correo\">\n' );
document.write( '          <i class=\"datos fas fa-envelope mr-3\"></i> contimex@contimex.com</p>\n' );
document.write( '        <p class=\"telefono\">\n' );
document.write( '          <i class=\"datos fas fa-phone mr-3\"></i> 01 800 849 9888</p>\n' );
document.write( '        <p class=\"telcel\">\n' );
document.write( '          <i class=\"datos fas fa-print mr-3\"></i> Cel: (044) 55 39 96 63 87</p>\n' );
document.write( '\n' );
document.write( '      </div>\n' );
document.write( '      <!-- Grid column -->\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '    <!-- Grid row -->\n' );
document.write( '\n' );
document.write( '  </div>\n' );
document.write( '  <!-- Footer Links -->\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '  <div style=\"background-color:#000;\">\n' );
document.write( '    <div class=\"container\">\n' );
document.write( '\n' );
document.write( '      <!-- Grid row-->\n' );
document.write( '      <div class=\"row py-4 d-flex align-items-center\">\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '        <!-- Grid column -->\n' );
document.write( '        <div class=\"copyright footer-copyright text-center py-3\">© 2020 Copyright:\n' );
document.write( '          <a href=\"https://mdbootstrap.com/education/bootstrap/\">Todos los derechos reservados</a>\n' );
document.write( '        </div>\n' );
document.write( '        <!-- Grid column -->\n' );
document.write( '        <div class=\"col-md-6 col-lg-7 text-center text-md-right\">\n' );
document.write( '\n' );
document.write( '          <!-- Facebook -->\n' );
document.write( '          <a class=\"fb-ic\">\n' );
document.write( '            <i class=\"fab fa-facebook-f white-text mr-4\" style=\"color:#fff;\"> </i>\n' );
document.write( '          </a>\n' );
document.write( '          <!-- Twitter -->\n' );
document.write( '          <a class=\"tw-ic\">\n' );
document.write( '            <i class=\"fab fa-twitter white-text mr-4\" style=\"color:#fff;\"> </i>\n' );
document.write( '          </a>\n' );
document.write( '          <!-- Google +-->\n' );
document.write( '          <a class=\"gplus-ic\">\n' );
document.write( '            <i class=\"fab fa-google-plus-g white-text mr-4\" style=\"color:#fff;\"> </i>\n' );
document.write( '          </a>\n' );
document.write( '          <!--Linkedin -->\n' );
document.write( '          <a class=\"li-ic\">\n' );
document.write( '            <i class=\"fab fa-linkedin-in white-text mr-4\" style=\"color:#fff;\"> </i>\n' );
document.write( '          </a>\n' );
document.write( '          <!--Instagram-->\n' );
document.write( '          <a class=\"ins-ic\">\n' );
document.write( '            <i class=\"fab fa-instagram white-text\" style=\"color:#fff;\"> </i>\n' );
document.write( '          </a>\n' );
document.write( '\n' );
document.write( '        </div>\n' );
document.write( '        <!-- Grid column -->\n' );
document.write( '\n' );
document.write( '      </div>\n' );
document.write( '      <!-- Grid row-->\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '  </div>\n' );
document.write( '\n' );
document.write( '</footer>\n' );
document.write( '<!-- Footer -->\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '      <!-- Optional JavaScript -->\n' );
document.write( '      <!-- jQuery first, then Popper.js, then Bootstrap JS -->\n' );
document.write( '      <script src=\"https://code.jquery.com/jquery-3.4.1.slim.min.js\" integrity=\"sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n\" crossorigin=\"anonymous\"></script>\n' );
document.write( '      <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\n' );
document.write( '      <script src=\"js/bootstrap.min.js\"></script>\n' );
document.write( '      <script src=\"js/estilos.js\"></script>\n' );
document.write( '\n' );
document.write( '    </body>\n' );
document.write( '    </html>\n' );
