document.write( '<!DOCTYPE html>\n' );
document.write( '<html lang=\"es\">\n' );
document.write( '<head>\n' );
document.write( '<!-- Required meta tags -->\n' );
document.write( '<meta charset=\"utf-8\">\n' );
document.write( '<!-- Esta linea de codigo hace que la pagina sea responsive -->\n' );
document.write( '<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scalable=1.0, minimum-scale=1.0 shrink-to-fit=no\">\n' );
document.write( '\n' );
document.write( '<!-- Con esta linea estamos agregando Bootstrap CSS -->\n' );
document.write( '<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n' );
document.write( '<!-- Con esta linea estamos agregando los estilos css, se hiso un archivo de estilos en la carpeta css -->\n' );
document.write( '<link rel=\"stylesheet\" href=\"css/estilos.css\">\n' );
document.write( '<!-- link para agregar nuevas fuentes y el script para los iconos de fontawesome -->\n' );
document.write( '<link href=\"https://fonts.googleapis.com/css?family=Courgette&display=swap\" rel=\"stylesheet\">\n' );
document.write( '<script src=\"https://kit.fontawesome.com/538a96cd4c.js\" crossorigin=\"anonymous\"></script>\n' );
document.write( '<!-- scrollreveal-->\n' );
document.write( '<script src=\"https://unpkg.com/scrollreveal\"></script>\n' );
document.write( '<!-- titulo que aparecerá en la pestaña de la pagina -->\n' );
document.write( '<title >Pinturas Contimex</title>\n' );
document.write( '</head>\n' );
document.write( '\n' );
document.write( '<body>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '<header>\n' );
document.write( '  <div class=\"logo_contimex\">\n' );
document.write( '  <a href=\"index.html\">  <img src=\"img/ctmx.png\" width=\"300\" height=\"80\" alt=\"error de imagen\"></a>\n' );
document.write( '<a class=\"quiero\" href=\"\">¿QUIERES SER DISTRIBUIDOR?\n' );
document.write( '     <i class=\"icono1 fas fa-truck-moving\"></i></a>\n' );
document.write( '\n' );
document.write( '     <a class=\"ubica\" href=\"contacto.html\">UBICA TU TIENDA\n' );
document.write( '     CONTIMEX\n' );
document.write( '    <i class=\"icono2 fas fa-map-marker-alt\"></i></a>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <a href=\"https://www.facebook.com/pinturas.contimex/\"> <i class=\"fb  fab fa-facebook-square\"></i></a>\n' );
document.write( '    <a href=\"https://twitter.com/?lang=es\"><i class=\"tw fab fa-twitter\"></i></a>\n' );
document.write( '    <a href=\"https://www.instagram.com/?hl=es-la\"><i class=\"itg fab fa-instagram\"></i></a>\n' );
document.write( '  </div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '<!-- se puede poner tambien expand-md para modificar el tamaño del responsive -->\n' );
document.write( '  <nav  class=\"navbar navbar-expand-lg\" role=\"navigation\">\n' );
document.write( '\n' );
document.write( '    <a class=\"navbar-brand\" href=\"index.html\">\n' );
document.write( '    </a>\n' );
document.write( '\n' );
document.write( '    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n' );
document.write( '      <span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '    </button>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n' );
document.write( '      <ul class=\"menu\">\n' );
document.write( '\n' );
document.write( '        <li class=\"nav-item active\">\n' );
document.write( '          <a class=\"nav-link\" href=\"index.html\">INICIO <span class=\"sr-only\">(current)</span></a>\n' );
document.write( '        </li>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '        <li class=\"nav-item dropdown\">\n' );
document.write( '                      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                        PRODUCTOS</a>\n' );
document.write( '\n' );
document.write( '                        <div class=\"submenu\" aria-labelledby=\"navbarDropdown\">\n' );
document.write( '                          <a class=\"dropdown-item\" href=\"vinilicas.html\">Vinilicas</a>\n' );
document.write( '                          <a class=\"dropdown-item\" href=\"esmaltes.html\">Esmaltes</a>\n' );
document.write( '                          <a class=\"dropdown-item\" href=\"impermeabilizantes.html\">Impermeabilizantes</a>\n' );
document.write( '                          <a class=\"dropdown-item\" href=\"pegamentos.html\">Pegamentos y selladores</a>\n' );
document.write( '                          <a class=\"dropdown-item\" href=\"especialidades.html\">Especialidades</a>\n' );
document.write( '                          <a class=\"dropdown-item\" href=\"industrial.html\">Industriales</a>\n' );
document.write( '\n' );
document.write( '                        </div>\n' );
document.write( '                      </li>\n' );
document.write( '                    </li>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '        <li class=\"nav-item\">\n' );
document.write( '          <a class=\"nav-link\"  href=\"nosotros.html\">NOSOTROS</a>\n' );
document.write( '          </li>\n' );
document.write( '\n' );
document.write( '          <li class=\"nav-item\">\n' );
document.write( '            <a class=\"nav-link\"  href=\"#\">CONTACTO</a>\n' );
document.write( '            </li>\n' );
document.write( '\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '              <a class=\"nav-link\"  href=\"#\">CHAT</a>\n' );
document.write( '              </li>\n' );
document.write( '\n' );
document.write( '          </ul>\n' );
document.write( '        </div>\n' );
document.write( '      </nav>\n' );
document.write( '    </header>\n' );
